[package]
name = "imgal_c"
version = "0.1.0"
authors = ["Edward Evans"]
edition = "2024"

[lib]
name = "imgal_c"
crate-type = ["cdylib", "rlib"]
doc = false

[dependencies]
imgal = { path = "../imgal" }
ndarray = "0.16.1"
